### ISSUE TITLE
Individual Survey - David

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldSoftwareCarpentry/InstructorTraining2015#13]
Need to fill in this survey

https://docs.google.com/a/sheffield.ac.uk/forms/d/1aXlqxFk6uJbB0k7QICteI5CP3lVczZKyjmgeNibX0Oc/viewform

**Comment by drj11** [comment]
Do these first:
- [ ] #24
- [ ] #5

**Comment by drj11** [comment]
99% sure I pressed submit, but I've emailed and asked.
