### ISSUE TITLE
Individual Survey - Anna

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldSoftwareCarpentry/InstructorTraining2015#14]
Need to fill in this survey

https://docs.google.com/a/sheffield.ac.uk/forms/d/1aXlqxFk6uJbB0k7QICteI5CP3lVczZKyjmgeNibX0Oc/viewform

**Comment by mikecroucher** [comment]
Anna. Have you done this?

**Comment by annakrystalli** [comment]
Yes, did that on monday
