### ISSUE TITLE
Submit mini-bio to SC repo - Drew

### ISSUE THREAD

**Issue by willfurnass** [SheffieldSoftwareCarpentry/InstructorTraining2015#19]
In addition to posting mini-bios here, we also need to submit them to SC repo via a pull request as follows:

"People who wish to teach Software Carpentry must submit a small pull request to a [specified GitHub repository](https://github.com/swcarpentry/training-prep-2015-09). Your pull request should contain one file (and one file only) called "your_name.txt" (e.g., marie_curie.txt or alan_turing.txt). This file should contain a sentence or two that describes the type of work you do. You will submit the name of this file as part of your application.

**Comment by drewleonard42** [comment]
I have.

**Comment by drj11** [comment]
Done in https://github.com/swcarpentry/training-prep-2015-09/pull/140
